neo_docking2:
  ros__parameters:
    # The offset pose from the origin of the docking station
    offset_x: 0.57
    offset_y: -0.26
    offset_yaw: -0.56 # calibrate it until the necessary orientation for docking is reached

    # Scan topic that needs to considered for the contour matching
    scan_topic: "/lidar_1/scan_filtered"

    # Undocking distance - for now only in x-direction
    undock_dist: 0.5

    # position of the pose before docking - just give the absolute pose
    # Contour matching algorithm takes of the inverse
    # In short - No negative value
    pre_dock_dist: 0.55

    # Distance from the docking station at which approach mode is enabled,
    # plus the tolerance applied to that threshold (metres).
    approach_distance: 0.37
    distance_tolerance: 0.005
